import 'package:hive/hive.dart';
import 'package:moneymanager/aisupport/models/phase_hive.dart';

part 'user_plan_hive.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 0)
class UserPlanHive extends HiveObject {
  @HiveField(0)
  String goalName; // This will be the key for the box or a primary identifier

  @HiveField(1)
  String earnThisYear;

  @HiveField(2)
  String currentSkill;

  @HiveField(3)
  String preferToEarnMoney;

  @HiveField(4)
  String note;

  @HiveField(5)
  List<PhaseHive> phases;

  @HiveField(6)
  String? duration;

  @HiveField(7)
  DateTime createdAt;

  

  UserPlanHive({
    required this.goalName,
    required this.earnThisYear,
    required this.currentSkill,
    required this.preferToEarnMoney,
    required this.note,
    required this.phases,
    required this.createdAt,
    required this.duration,
  });
}